# Generated by Django 6.0.2 on 2026-02-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('target_audience', models.TextField()),
                ('business_model', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('e-commerce', 'E-commerce'), ('food', 'Food & Beverage'), ('travel', 'Travel'), ('real_estate', 'Real Estate'), ('entertainment', 'Entertainment'), ('social', 'Social Impact'), ('other', 'Other')], default='technology', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_strengths', models.JSONField(blank=True, default=list)),
                ('ai_weaknesses', models.JSONField(blank=True, default=list)),
                ('ai_market_score', models.FloatField(blank=True, null=True)),
                ('ai_trend_analysis', models.TextField(blank=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('vote_score', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_ideas',
                'ordering': ['-vote_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ideas.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.startupidea')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='ideas.startupidea')),
            ],
            options={
                'db_table': 'bookmarks',
                'unique_together': {('idea', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.startupidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'unique_together': {('idea', 'user')},
            },
        ),
    ]
